export * from './home/home.component'
export * from './about/about.component'
export * from './contact/contact.component'
export * from './factory/factory.component'
export * from './certifications/certifications.component'
export * from './blog/blog.component'
export * from './page-not-found/page-not-found.component'